version: '3.8'

x-args: &args
  args:
    BUILD_TAG: ${BUILD_TAG:-local}

services:
  dinosauria-bot:
    image: ${REGISTRY}${REPOSITORY}dinosauria-bot:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      <<: *args
      target: dinosauria-bot
    env_file:
      - dinosauria-bot.env
    restart: unless-stopped
